### ISSUE TITLE
extDB2 Issue

### ISSUE THREAD

**Issue by Markkos26** [A3Armory/A3A_A3Wasteland.Tanoa#2]
My server does not start, it gets stuck in "Welcome to A3Wasteland, please wait for your client to initialize".
Here's the server log:

"[extDB2] ███ Protocol Error: [0,""Error Statement Exception""], Unique ID: 113"
 4:41:16 "-- LOOTSPAWNER LSusedclass_list ready, d: 15.3569s"
 4:41:16 "-- LOOTSPAWNER LSDer started..."
 4:41:16 "Creating Storage at: Momea ([10138.6,13326.1,24.2229])"
 4:41:17 "[extDB2] Sleep [4]: 6054.87"

any idea? im using the typical 'a3wasteland_db_v2.05.sql' from [A3Wasteland/Release_Files](https://www.google.com.ar/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwit4fG8p5LSAhXHlZAKHbt7DVQQjBAIJTAC&url=https%3A%2F%2Fgithub.com%2FA3Wasteland%2FRelease_Files&usg=AFQjCNG-qdenMGpZghc_0CyR4mGUGt1lww&bvm=bv.146786187,d.Y2I) in my database

**Comment by AgentRev** [comment]
You need to post FULL server log.

**Comment by Markkos26** [comment]
ok:
[arma3server_2017-02-15_03-00-22.txt](https://github.com/A3Armory/A3A_A3Wasteland.Tanoa/files/777327/arma3server_2017-02-15_03-00-22.txt)

thanks!!!

**Comment by codexGW** [comment]
If you are using our mission you might need to add [this](https://github.com/A3Armory/A3A_A3Wasteland.Altis/blob/dev/addons/UniformPainter/SQL%20commands.sql). That's the only thing I can think of other than the bounty system. Unless you are using the A3Armory mission and have problems with a addon not included in vanilla A3Wasteland [this is where the main repos are](https://github.com/A3Wasteland). We are just a 3 server community with a few addons added to A3Wasteland. This is the best place for overall issues with A3Wasteland.
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues

**Comment by Markkos26** [comment]
Perfect, thanks a lot! i will try to fix it with your info.

**Comment by codexGW** [comment]
No problem. It was just a couple guesses though. Make sure you use the latest versions too. Not sure whats going on with this [file](https://github.com/A3Armory/A3A_A3Wasteland.Tanoa/blob/master/server/missions/factoryMethods/createUnits/sniperGroup.sqf). Your rpt is full of errors from that. Can't tell you what the issue with extDB is. Try a program called Beyond Compare and test the difference between your mission and [ours](https://github.com/A3Armory/A3A_A3Wasteland.Tanoa/archive/master.zip).

**Comment by Markkos26** [comment]
Server is running!!! 
This on my database solved the error: 

ALTER TABLE `a3wasteland`.`playersave` 
ADD COLUMN `UniformTexture` VARCHAR(4096) NOT NULL DEFAULT '""' COMMENT '' AFTER `WastelandItems`,
ADD COLUMN `BackpackTexture` VARCHAR(4096) NOT NULL DEFAULT '""' COMMENT '' AFTER `UniformTexture`;

Thanks again!
